.gitignore, common/Cargo.toml, common/build.rs, common/proto/Envelope.proto, common/src/envelope.rs, common/src/lib.rs
Added definitons for the evelope from Client -> Server and from Server -> Client
=> Added protobuf definitions and tests

client/src/keygen.rs, client/src/lib.rs, client/src/storage/sqlite/signed_pre_key.rs, client/src/time.rs, common/Cargo.toml, common/src/api/account.rs, common/src/api/device.rs, common/src/api/keys.rs, common/src/api/mod.rs, common/src/error.rs, common/src/lib.rs, common/src/time.rs
this includes jsonable structures for devices, keys and accounts
=> Common api types

.sqlx/query-3e941a54f326cc4a2519171b8db39ca6b26e997874f87d2197199aca914f56a6.json, .sqlx/query-dfd29f2cba25e6c46ca516c509526ff06fa4f4785aa4e646e52908add12b47a4.json, .sqlx/query-eefe8dad53fafc5ca1f87975e57df85928963143230df957cb0de48960d02f96.json, client/database/migrations/20250204091337_client.sql, client/src/error.rs, client/src/storage/inmem/contact.rs, client/src/storage/sqlite/account.rs, client/src/storage/sqlite/contact.rs, client/src/storage/sqlite/identity.rs, client/src/storage/sqlite/kyber.rs, client/src/storage/sqlite/pre_key.rs, client/src/storage/sqlite/sender_key.rs, client/src/storage/sqlite/session.rs, client/src/storage/sqlite/signed_pre_key.rs, client/src/storage/traits/contact.rs, client/tests/conformance/contact.rs, client/tests/conformance/mod.rs
Contact store on client stores known devices for accounts ids.
Closes #42
=> Added contact store

.github/workflows/rust.yml, README.md
This pull request adds code coverage
=> Code Coverage

client/src/encryption/encrypt.rs, client/src/encryption/envelope.rs, client/src/encryption/mod.rs, client/src/encryption/padding.rs, client/src/error.rs, client/src/lib.rs, client/src/net/protocol/client.rs, client/src/net/protocol/error.rs, client/src/storage/sqlite/account.rs, common/build.rs, common/proto/Envelope.proto, common/src/protocol/mod.rs, server/src/logic/message.rs, server/src/protocol/message.rs, server/src/routes/websocket.rs
Added support for encryption of anything that implements Into<&[u8]>
Added support for decryption of anything that implements From<&[u8]>
=> Added encryption

client/src/client.rs, client/src/storage/inmem/mod.rs, client/src/storage/mod.rs, client/src/storage/sqlite/mod.rs, e2e/tests/message.rs, e2e/tests/utils/tls.rs
fixed bug where you could not receive a message from an unknown user. Removed load from store config
=> Fix Sqlite Store

e2e/tests/account.rs, server/src/managers/error.rs, server/src/managers/in_memory/account.rs
Now the server only takes unique usernames upon registration, this is also tested in e2e
=> Unique username

client/src/client.rs, client/src/error.rs, client/src/storage/key_generation.rs, server/src/logic/account.rs, server/src/managers/in_memory/account.rs, server/src/managers/traits/account_manager.rs
Renamed function, closes #91 
Investigated RouterError::NoDevicesInRequest, closes #90
Implemented helper function to create RegistrationPreKeys, closing #77 
Fixed typo, closing #92
=> Fixed comments

client/src/client.rs, client/src/net/api_trait.rs, client/src/net/http_client.rs, client/src/net/protocol/client.rs, client/src/net/protocol/error.rs, client/tests/conformance/kyber.rs, client/tests/conformance/pre_key.rs, client/tests/conformance/signed_pre_key.rs, e2e/tests/account.rs, e2e/tests/device.rs, e2e/tests/keys.rs, e2e/tests/message.rs, server/Cargo.toml
closes #86 
closes #88 
closes #79 
closes #83
=> Fix Issues found in mutual review

server/src/auth/authenticated_user.rs, server/src/auth/mod.rs
=> get_credentials function

.github/codecov.yml, Cargo.toml, README.md, client/src/net/error.rs, client/src/net/tls.rs, e2e/tests/account.rs, e2e/tests/message.rs, e2e/tests/utils/server.rs, server/Cargo.toml, server/src/config.rs, server/src/error.rs, server/src/lib.rs, server/src/main.rs, server/src/server.rs, server/src/tls.rs
- Added support for TLS configuration with mTLS
- Added error handling in server `main.rs`
- Server TLS Config from json
=> JSON Server TLS Config 

client/src/net/protocol/client.rs, client/src/net/protocol/decode.rs, client/src/net/protocol/error.rs, client/src/net/protocol/mod.rs, client/src/net/protocol/traits.rs
Moved SAM protocol logic into its own file
=> SAM Protocol decoder

.dockerignore, .github/workflows/docker.yml, Dockerfile, README.md, server/src/server.rs
=> Docker and docker action to push to ghcr

client/src/client.rs, client/src/logic/message.rs, client/src/logic/mod.rs, client/src/net/protocol/client.rs, client/src/net/protocol/mod.rs, client/src/net/protocol/traits.rs, client/src/net/protocol/websocket.rs, e2e/tests/device.rs, server/src/managers/in_memory/account.rs, server/src/managers/in_memory/device.rs, server/src/managers/in_memory/message.rs, server/src/managers/postgres/account.rs, server/src/managers/traits/account_manager.rs, server/src/managers/traits/device_manager.rs, server/src/managers/traits/key_manager.rs, server/src/managers/traits/message_manager.rs
This pr entails:
- A new e2e test where i test that delete_device() works
- Modification of the send_message logic such that the functions can be used in denim-on-sam
- Modification of creating a `WebsocketClient` such that functions can be reused on denim-on-sam
=> Added delete device test, modified send_message logic

client/src/net/protocol/client.rs, client/src/net/protocol/websocket.rs
=> Websocket Receiver now has responsibility to make its own channels

Cargo.toml, client/Cargo.toml, client/src/net/protocol/client.rs, client/src/net/protocol/websocket.rs, e2e/Cargo.toml, e2e/tests/account.rs, e2e/tests/device.rs, e2e/tests/keys.rs, e2e/tests/message.rs, server/Cargo.toml, server/src/routes/websocket.rs, test_utils/Cargo.toml, test_utils/src/lib.rs
The port oracle takes ports from 3080-3089, then 4080-4089 and so on. It can also be used in denim-on-sam 👍🏻
=> implemented port oracle

Cargo.toml, client/src/encryption/mod.rs, client/src/logic/message.rs, client/src/logic/mod.rs, client/src/storage/key_generation.rs, client/src/storage/mod.rs, common/Cargo.toml, common/src/api/keys.rs, common/src/api/mod.rs
- allows us to resuse logic in denim-on-sam
=> Export Encryption & Encoding of keys

client/src/storage/error.rs, client/src/storage/sqlite/message.rs, client/src/storage/sqlite/mod.rs, client/src/storage/sqlite/sqlite_connector.rs, client/tests/conformance/mod.rs, e2e/tests/account.rs, e2e/tests/device.rs, e2e/tests/keys.rs, e2e/tests/message.rs
users of sam libs can now create sqlite connections without having dependency on sqlx
closes #132
=> SQLite connector

client/src/encryption/encrypt.rs, client/src/logic/account.rs, client/src/logic/device.rs, client/src/logic/key.rs, client/src/logic/message.rs, client/src/net/http_client.rs, client/src/net/protocol/client.rs, client/src/net/protocol/mod.rs, client/src/storage/error.rs, client/src/storage/inmem/kyber.rs, client/src/storage/inmem/pre_key.rs, client/src/storage/inmem/signed_pre_key.rs, client/src/storage/sqlite/account.rs, client/src/storage/sqlite/contact.rs, client/src/storage/sqlite/identity.rs, client/src/storage/sqlite/kyber.rs, client/src/storage/sqlite/message.rs, client/src/storage/sqlite/pre_key.rs, client/src/storage/sqlite/sender_key.rs, client/src/storage/sqlite/session.rs, client/src/storage/sqlite/signed_pre_key.rs, server/src/managers/postgres/account.rs, server/src/protocol/message.rs, server/src/protocol/websocket.rs
=> More Logging

client/src/client.rs, client/src/storage/sqlite/sender_key.rs
=> Sender Key error fix, no more unwrap in client

README.md, server/src/config.rs, server/src/error.rs, server/src/main.rs, server/src/managers/postgres/mod.rs
=> PostgreSQL Integration

client/src/storage/error.rs, client/src/storage/inmem/message.rs, client/src/storage/sqlite/message.rs
=> Dead Receiver bug fixed

client/src/client.rs, e2e/tests/account.rs, e2e/tests/device.rs, e2e/tests/message.rs
Now you dont have to handle a result when trying to get your own account id and device id
=> Clients own account id and device id is now also on the client struct

client/src/storage/sqlite/identity.rs, client/src/storage/sqlite/message.rs, client/src/storage/sqlite/mod.rs, client/tests/conformance/mod.rs, e2e/tests/account.rs, e2e/tests/device.rs, e2e/tests/keys.rs, e2e/tests/message.rs, server/src/main.rs
Sqlconnector is now taken as argument on config
=> Made sqlite config the same as denim
